version: "3.8"
services:
  app:
    build: .
    ports:
      - "${APP_PORT}:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: "${APP_PORT}"
    depends_on:
      - db
    command:
      ["./wait-for-it.sh", "db:5432", "--timeout=60", "--", "npm run start"]

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      retries: 5

  prisma:
    image: node:20-alpine
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: ["npx", "prisma", "db", "push"]

volumes:
  db-data:
